//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.SalesOrderHeader = new HashSet<SalesOrderHeader>();
            this.Item = new HashSet<Item>();
            this.Item1 = new HashSet<Item>();
        }
    
        public int CustomerID { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> CreditCardID { get; set; }
        public string PaypalAccount { get; set; }
        public string DefaultPaymentMethod { get; set; }
        public string Phone { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<Item> Item1 { get; set; }
    }
}
