//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemPictures = new HashSet<ItemPicture>();
            this.ItemSizes = new HashSet<ItemSize>();
            this.SalesOrderRows = new HashSet<SalesOrderRow>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.Categories = new HashSet<Category>();
            this.Colors = new HashSet<Color>();
            this.Materials = new HashSet<Material>();
            this.Occasions = new HashSet<Occasion>();
            this.Styles = new HashSet<Style>();
            this.UserProfiles1 = new HashSet<UserProfile>();
        }
    
        public int ItemID { get; set; }
        public string Name { get; set; }
        public string ProductNumber { get; set; }
        public Nullable<short> LowStockWarningLevel { get; set; }
        public Nullable<double> ListPrice { get; set; }
        public Nullable<double> StandardCost { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<int> DaysToMake { get; set; }
        public System.DateTime SellStartDate { get; set; }
        public Nullable<System.DateTime> SellEndDate { get; set; }
        public int CategoryID { get; set; }
        public string Gender { get; set; }
        public string ItemGUID { get; set; }
        public int Length { get; set; }
    
        public virtual ICollection<ItemPicture> ItemPictures { get; set; }
        public virtual ICollection<ItemSize> ItemSizes { get; set; }
        public virtual ICollection<SalesOrderRow> SalesOrderRows { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Color> Colors { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ICollection<Occasion> Occasions { get; set; }
        public virtual ICollection<Style> Styles { get; set; }
        public virtual ICollection<UserProfile> UserProfiles1 { get; set; }
    }
}
