//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSize
    {
        public int ItemID { get; set; }
        public int SizeID { get; set; }
        public int StockLevel { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Size Size { get; set; }
    }
}
