//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public string MaterialDesc { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
    }
}
