//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.ItemPictures = new HashSet<ItemPicture>();
        }
    
        public int PictureID { get; set; }
        public byte[] ThumbnailPic { get; set; }
        public string LargePictureAddress { get; set; }
    
        public virtual ICollection<ItemPicture> ItemPictures { get; set; }
    }
}
