//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.SalesOrderHeader = new HashSet<SalesOrderHeader>();
            this.SalesOrderRow = new HashSet<SalesOrderRow>();
        }
    
        public int PromotionID { get; set; }
        public string PromotionName { get; set; }
        public int DiscountType { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string PromoCode { get; set; }
    
        public virtual ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
        public virtual ICollection<SalesOrderRow> SalesOrderRow { get; set; }
    }
}
