//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderRow
    {
        public int SalesOrderID { get; set; }
        public int SalesOrderRowID { get; set; }
        public string CarrierTrackingNumber { get; set; }
        public int OrderQty { get; set; }
        public int ItemID { get; set; }
        public double UnitPrice { get; set; }
        public double LineTotal { get; set; }
        public int SalesOrderRowGUID { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<int> ShipMethodID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual SalesOrderHeader SalesOrderHeader { get; set; }
        public virtual ShipMethod ShipMethod { get; set; }
    }
}
