//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderHeader
    {
        public SalesOrderHeader()
        {
            this.SalesOrderRow = new HashSet<SalesOrderRow>();
        }
    
        public int SalesOrderID { get; set; }
        public int ShipMethodID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string Status { get; set; }
        public int BillToAddressID { get; set; }
        public int ShipToAddressID { get; set; }
        public int CreditCardID { get; set; }
        public double SubTotal { get; set; }
        public double TaxAmt { get; set; }
        public double Freight { get; set; }
        public double TotalDue { get; set; }
        public int SalesOrderGUID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual CreditCard CreditCard { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ShipMethod ShipMethod { get; set; }
        public virtual ICollection<SalesOrderRow> SalesOrderRow { get; set; }
    }
}
