//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipMethod
    {
        public ShipMethod()
        {
            this.SalesOrderHeader = new HashSet<SalesOrderHeader>();
            this.SalesOrderRow = new HashSet<SalesOrderRow>();
        }
    
        public int ShipMethodID { get; set; }
        public string Name { get; set; }
        public string TrackingURL { get; set; }
    
        public virtual ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
        public virtual ICollection<SalesOrderRow> SalesOrderRow { get; set; }
    }
}
