//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingBagRow
    {
        public int CustomerID { get; set; }
        public int RowID { get; set; }
        public int OrderQty { get; set; }
        public int ItemID { get; set; }
        public double UnitPrice { get; set; }
    
        public virtual ShoppingBag ShoppingBag { get; set; }
    }
}
