//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.ItemSizes = new HashSet<ItemSize>();
        }
    
        public int SizeID { get; set; }
        public byte[] SizeName { get; set; }
    
        public virtual ICollection<ItemSize> ItemSizes { get; set; }
    }
}
