//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTDBEntities : DbContext
    {
        public TTDBEntities()
            : base("name=TTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Address { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Color> Color { get; set; }
        public DbSet<ColorMapping> ColorMapping { get; set; }
        public DbSet<CountryRegion> CountryRegion { get; set; }
        public DbSet<CreditCard> CreditCard { get; set; }
        public DbSet<Item> Item { get; set; }
        public DbSet<ItemPicture> ItemPicture { get; set; }
        public DbSet<ItemSize> ItemSize { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Occasion> Occasion { get; set; }
        public DbSet<Picture> Picture { get; set; }
        public DbSet<Promotion> Promotion { get; set; }
        public DbSet<SalesOrderHeader> SalesOrderHeader { get; set; }
        public DbSet<SalesOrderRow> SalesOrderRow { get; set; }
        public DbSet<ShipMethod> ShipMethod { get; set; }
        public DbSet<ShoppingBag> ShoppingBag { get; set; }
        public DbSet<ShoppingBagRow> ShoppingBagRow { get; set; }
        public DbSet<Size> Size { get; set; }
        public DbSet<StateProvince> StateProvince { get; set; }
        public DbSet<Style> Style { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
