//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTDBEntities : DbContext
    {
        public TTDBEntities()
            : base("name=TTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<ColorMapping> ColorMappings { get; set; }
        public DbSet<CountryRegion> CountryRegions { get; set; }
        public DbSet<CreditCard> CreditCards { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemPicture> ItemPictures { get; set; }
        public DbSet<ItemSize> ItemSizes { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<Occasion> Occasions { get; set; }
        public DbSet<Picture> Pictures { get; set; }
        public DbSet<SalesOrderHeader> SalesOrderHeaders { get; set; }
        public DbSet<SalesOrderRow> SalesOrderRows { get; set; }
        public DbSet<ShipMethod> ShipMethods { get; set; }
        public DbSet<Size> Sizes { get; set; }
        public DbSet<StateProvince> StateProvinces { get; set; }
        public DbSet<Style> Styles { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
    }
}
