//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleniGeorge.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.SalesOrderHeader = new HashSet<SalesOrderHeader>();
            this.Item = new HashSet<Item>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string UserName { get; set; }
        public string Suffix { get; set; }
        public string CreditCardID { get; set; }
        public string PaypalAccount { get; set; }
        public string DefaultPaymentMethod { get; set; }
        public string Phone { get; set; }
        public Nullable<int> AddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual CreditCard CreditCard { get; set; }
        public virtual ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
        public virtual ShoppingBag ShoppingBag { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
